name: Debug Variables

on:
  workflow_call:

jobs:
  Explore-GitHub-Actions:
    runs-on: [arc-runner-set-ubuntu-base]

    steps:
    - name: Debug github context
      run: |
        # Debug the secret or environment variable by printing its value
        echo "The github actor is: ${{ github.actor }}"
        echo "The github repo owner is: ${{ github.repository_owner }}"

    - run: echo "🎉 This job used my self hosted runner!"
